const ICON_BASE = '/icons/beauty-line-art';

export const WHATSAPP_NUMBER = '918072966960';

export const QUOTATION_GROUPS = [
  {
    id: 'makeup',
    title: 'Makeup',
    items: [
      { id: 'bridal-makeup', name: 'Bridal Makeup', iconPath: `${ICON_BASE}/bridalmakeup.png`, featured: true },
      { id: 'party-makeup', name: 'Party Makeup', iconPath: `${ICON_BASE}/party makeup.png`, featured: true },
      { id: 'engagement-makeup', name: 'Engagement Makeup', iconPath: `${ICON_BASE}/bridalmakeup.png` },
      { id: 'hd-makeup', name: 'HD Makeup', iconPath: `${ICON_BASE}/bridalmakeup.png` },
      { id: 'airbrush-makeup', name: 'Airbrush Makeup', iconPath: `${ICON_BASE}/bridalmakeup.png`, featured: true },
      { id: 'glass-glow-makeup', name: 'Glass Glow Makeup', iconPath: `${ICON_BASE}/facial.png`, featured: true },
    ],
  },
  {
    id: 'skin-care',
    title: 'Skin Care',
    items: [
      { id: 'facials', name: 'Facials', iconPath: `${ICON_BASE}/facial.png` },
      { id: 'clean-up', name: 'Clean-up', iconPath: `${ICON_BASE}/facial.png` },
      { id: 'skin-polishing', name: 'Skin Polishing', iconPath: `${ICON_BASE}/facial.png`, featured: true },
      { id: 'de-tan-treatment', name: 'De-tan Treatment', iconPath: `${ICON_BASE}/facial.png` },
      { id: 'bleach', name: 'Bleach', iconPath: `${ICON_BASE}/facial.png` },
      { id: 'eyebrow-threading', name: 'Eyebrow Threading', iconPath: `${ICON_BASE}/facial.png` },
      { id: 'upper-lip-threading', name: 'Upper Lip Threading', iconPath: `${ICON_BASE}/facial.png` },
      { id: 'forehead-threading', name: 'Forehead Threading', iconPath: `${ICON_BASE}/facial.png` },
    ],
  },
  {
    id: 'hair-care',
    title: 'Hair Care',
    items: [
      { id: 'hair-cut', name: 'Hair Cut', iconPath: `${ICON_BASE}/haircut.png` },
      { id: 'hair-wash', name: 'Hair Wash', iconPath: `${ICON_BASE}/hairspa.png` },
      { id: 'hair-spa', name: 'Hair Spa', iconPath: `${ICON_BASE}/hairspa.png`, featured: true },
      { id: 'hair-coloring', name: 'Hair Coloring', iconPath: `${ICON_BASE}/haircolouring.png` },
      { id: 'hair-straightening', name: 'Hair Straightening', iconPath: `${ICON_BASE}/hairspa.png` },
      { id: 'hair-smoothening', name: 'Hair Smoothening', iconPath: `${ICON_BASE}/hairspa.png` },
      { id: 'keratin-treatment', name: 'Keratin Treatment', iconPath: `${ICON_BASE}/hairspa.png`, featured: true },
    ],
  },
  {
    id: 'body-care',
    title: 'Body Care',
    items: [
      { id: 'manicure', name: 'Manicure', iconPath: `${ICON_BASE}/manicure.png`, featured: true },
      { id: 'pedicure', name: 'Pedicure', iconPath: `${ICON_BASE}/pedicure.png`, featured: true },
      { id: 'gel-polish', name: 'Gel Polish', iconPath: `${ICON_BASE}/manicure.png` },
      { id: 'nail-extensions', name: 'Nail Extensions', iconPath: `${ICON_BASE}/manicure.png`, featured: true },
      { id: 'full-arms-waxing', name: 'Full Arms Waxing', iconPath: `${ICON_BASE}/waxing.png` },
      { id: 'full-legs-waxing', name: 'Full Legs Waxing', iconPath: `${ICON_BASE}/waxing.png` },
      { id: 'underarm-waxing', name: 'Underarm Waxing', iconPath: `${ICON_BASE}/waxing.png` },
      { id: 'face-waxing', name: 'Face Waxing', iconPath: `${ICON_BASE}/waxing.png` },
      { id: 'rica-wax', name: 'Rica Wax', iconPath: `${ICON_BASE}/waxing.png` },
      { id: 'polishing', name: 'Polishing', iconPath: `${ICON_BASE}/facial.png` },
      { id: 'body-detan-treatment', name: 'Detan Treatment', iconPath: `${ICON_BASE}/facial.png` },
    ],
  },
  {
    id: 'bridal-services',
    title: 'Bridal Services',
    items: [
      { id: 'bridal-packages', name: 'Bridal Packages', iconPath: `${ICON_BASE}/bridalmakeup.png`, featured: true },
      { id: 'pre-bridal-treatments', name: 'Pre-Bridal Treatments', iconPath: `${ICON_BASE}/facial.png`, featured: true },
      { id: 'saree-draping-pre-pleating', name: 'Saree Draping / Pre-Pleating', iconPath: `${ICON_BASE}/bridalmakeup.png` },
      { id: 'hairstyling', name: 'Hairstyling', iconPath: `${ICON_BASE}/haircut.png` },
      { id: 'mehendi', name: 'Mehendi', iconPath: `${ICON_BASE}/manicure.png` },
      { id: 'jewellery', name: 'Jewellery', iconPath: `${ICON_BASE}/bridalmakeup.png` },
      { id: 'flowers', name: 'Flowers', iconPath: `${ICON_BASE}/bridalmakeup.png` },
      { id: 'lens-lashes', name: 'Lens / Lashes', iconPath: `${ICON_BASE}/bridalmakeup.png` },
    ],
  },
  {
    id: 'bridal-packages',
    title: 'Bridal Packages',
    items: [
      {
        id: 'pro-hd-makeup-package',
        name: 'Pro HD Bridal Package',
        iconPath: `${ICON_BASE}/bridalmakeup.png`,
        package: true,
        featured: true,
        badgeLabel: 'Special Offer 01',
        tagline: 'Flawless HD Finish • Timeless Elegance',
        priceLabel: '₹15,000',
        priceContext: '1 Event',
        offerLabel: '2 Events Only ₹25,000',
        description: 'A luxurious HD bridal makeover that enhances your natural beauty with a flawless, camera-ready finish.',
        highlights: [
          'Cleaner Facial & Brightening Facial',
          'Premium Antique Jewellery',
          'Contact Lens & Lashes Included',
          'Saree Pre-Pleating & Saree Changeover',
          'Long-Lasting HD Bridal Finish',
        ],
        benefits: ['Wedding', 'Reception', 'Engagement'],
        footerLabel: 'Perfect for Weddings, Reception & Engagements',
        note: '2 Events ₹25,000 special offer | 3 Events ₹35,000 | Advance ₹3,000 | Travel separate',
      },
      {
        id: 'luxury-airbrush-bridal-package',
        name: 'Luxury Airbrush Bridal Package',
        iconPath: `${ICON_BASE}/bridalmakeup.png`,
        package: true,
        featured: true,
        badgeLabel: 'Special Offer 02',
        tagline: 'Luxury Finish • Lightweight Feel • All-Day Perfection',
        priceLabel: '₹20,000',
        offerLabel: 'Exclusive Offer Available for Multiple Events',
        description: 'Premium silicone-based airbrush makeup for a radiant complexion that stays fresh throughout your celebration.',
        highlights: [
          'Pre-Bridal Facial Included',
          'Hydra Facial Treatment',
          'Professional Bridal Jewellery',
          'Original Flowers Included',
          '2 Saree Pre-Pleating & Draping Services',
        ],
        benefits: ['Sweat Resistant', 'Lightweight Coverage', 'Long-Lasting Glow'],
        footerLabel: 'Luxury bridal coverage designed for all-day perfection',
        note: 'Special offer on booking 2 events',
      },
      {
        id: 'silver-package-hd-makeup',
        name: 'Silver Package – HD Makeup',
        iconPath: `${ICON_BASE}/bridalmakeup.png`,
        package: true,
        badgeLabel: 'Special Offer 03',
        tagline: 'Elegant Bridal Beauty at an Affordable Price',
        priceLabel: '₹10,000',
        offerLabel: 'Best Value Bridal Package',
        description: 'A complete HD bridal package for brides seeking a naturally beautiful, polished wedding look.',
        highlights: [
          'HD Bridal Makeup',
          'Basic Bridal Jewellery Set',
          'Lens, Lashes & Floral Hair Accessories',
          'Cleanup Facial & De-Tan Treatment',
          'Bleach & Threading',
        ],
        benefits: ['Skin-Like Finish', 'No Flashback', 'Natural Radiance'],
        footerLabel: 'Best Value Bridal Package',
        note: 'Travelling charges separate',
      },
      {
        id: 'gold-package-premium-choice',
        name: 'Gold Package – Premium Choice',
        iconPath: `${ICON_BASE}/bridalmakeup.png`,
        package: true,
        featured: true,
        badgeLabel: 'Special Offer 04',
        tagline: 'Our Most Popular Bridal Package',
        priceLabel: '₹12,000',
        offerLabel: 'Premium Choice for Modern Brides',
        description: 'A premium bridal experience with luxury products, enhanced accessories, and a sophisticated bridal finish.',
        highlights: [
          'Gold Facial & Gold Bleach Treatment',
          'Professional Threading',
          'Premium Lens, Lashes & Bridal Jewellery',
          'Original Fresh Flowers',
          'Professional Hair Styling & Hairdo',
        ],
        benefits: ['Premium Products', 'Luxury Accessories', 'Complete Styling'],
        footerLabel: 'Premium Choice for Modern Brides',
        note: 'Our most popular premium bridal package',
      },
    ],
  },
];
